### ISSUE TITLE
error running assemble

### ISSUE THREAD

**Issue by Gon1976** [FreBio/komics#2]
Hi,
I am try to run step by step.
From illumina reads, first assemble:
komics assemble --threads 4 --kmin 99 --kmax 119 --kstep 10 AM minic/AM_R1.fastq.gz minic/AM_R2.fastq.gz

blastn -out /home/ggreif/tmp.AM64.maxicircle.xml -outfmt 5 -query tmp.AM_megahit/AM.contigs.fa -evalue 1e-06 -subject /home/ggreif/.local/lib/python3.8/site-packages/komics/maxicircles.fasta -task megablast -dust no

Traceback (most recent call last):
  File "/home/ggreif/.local/bin/komics", line 46, in <module>
    exec('komics.commands.' + command + '.main()')
  File "<string>", line 1, in <module>
  File "/home/ggreif/.local/lib/python3.8/site-packages/komics/commands/assemble.py", line 38, in main
    ka.run()
  File "/home/ggreif/.local/lib/python3.8/site-packages/komics/assemble.py", line 137, in run
    self.blast_run()
  File "/home/ggreif/.local/lib/python3.8/site-packages/komics/assemble.py", line 105, in blast_run
    stdout, stderr=blastcmd()
  File "/home/ggreif/.local/lib/python3.8/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'blastn -out /home/ggreif/tmp.AM.maxicircle.xml -outfmt 5 -query tmp.AM64_megahit/AM.contigs.fa -evalue 1e-06 -subject /home/ggreif/.local/lib/python3.8/site-packages/komics/maxicircles.fasta -task megablast -dust no', message 'Command line argument error: Argument "query". File is not accessible:  `tmp.AM_megahit/AM.contigs.fa\''

Could you help me with this error.

Another approach I make is start to circularize nanopore minicircle reads (not really assembled contigs, but sure minicircles sequences with:
komics circularize AM minic/SeqsMinic_Nano.fasta
And return no sequence circular (but I know by reads length that should be circularized). The names of the reads should have a predetermined pattern? because mention that looks for _contig_ or some pattern in the name of reads (contigs)
Gonzalo

**Comment by Gon1976** [comment]
> Hi, I am try to run step by step. From illumina reads, first assemble: komics assemble --threads 4 --kmin 99 --kmax 119 --kstep 10 AM minic/AM_R1.fastq.gz minic/AM_R2.fastq.gz
> 
> blastn -out /home/ggreif/tmp.AM64.maxicircle.xml -outfmt 5 -query tmp.AM_megahit/AM.contigs.fa -evalue 1e-06 -subject /home/ggreif/.local/lib/python3.8/site-packages/komics/maxicircles.fasta -task megablast -dust no
> 
> Traceback (most recent call last): File "/home/ggreif/.local/bin/komics", line 46, in exec('komics.commands.' + command + '.main()') File "", line 1, in File "/home/ggreif/.local/lib/python3.8/site-packages/komics/commands/assemble.py", line 38, in main ka.run() File "/home/ggreif/.local/lib/python3.8/site-packages/komics/assemble.py", line 137, in run self.blast_run() File "/home/ggreif/.local/lib/python3.8/site-packages/komics/assemble.py", line 105, in blast_run stdout, stderr=blastcmd() File "/home/ggreif/.local/lib/python3.8/site-packages/Bio/Application/**init**.py", line 574, in **call** raise ApplicationError(return_code, str(self), stdout_str, stderr_str) Bio.Application.ApplicationError: Non-zero return code 1 from 'blastn -out /home/ggreif/tmp.AM.maxicircle.xml -outfmt 5 -query tmp.AM64_megahit/AM.contigs.fa -evalue 1e-06 -subject /home/ggreif/.local/lib/python3.8/site-packages/komics/maxicircles.fasta -task megablast -dust no', message 'Command line argument error: Argument "query". File is not accessible: `tmp.AM_megahit/AM.contigs.fa''
> 
> Could you help me with this error.
> 
> Another approach I make is start to circularize nanopore minicircle reads (not really assembled contigs, but sure minicircles sequences with: komics circularize AM minic/SeqsMinic_Nano.fasta And return no sequence circular (but I know by reads length that should be circularized). The names of the reads should have a predetermined pattern? because mention that looks for _contig_ or some pattern in the name of reads (contigs) Gonzalo

Solved the first part of the question. I haven't megahit correctly installed! 
Could you help-me with the second question about "circularize".
Gonzalo

**Comment by FreBio** [comment]
Hi there - sorry for the late reply.
Glad to hear you could solve your first problem. About the second problem, in principle circularize should work. How is the quality of the nanopore reads? If there are some erroneous base calling, then this might affect the circularization process. Also, how long are your reads? You might want to play around with minoverlap and maxoverlap parameters. Finally, whether these nanopore sequences are truly minicircles depend not only the length of the sequences (approx. 750 in Leishmania and 1000 in Trypanosoma) but also on the presence of CSB1, CSB2 and CSB3 mers. Have you checked whether the CSB3 are present? 

Best
Frederik

**Comment by Gon1976** [comment]
Hi Frederik
These are nanopore reads with good quality basecalled with Guppy5 (also I try with Canu corrected reads).
Also, I checked CSB3 is present because, previously I recover the minicircle reads using blast vs CSB3 (and filter by length only reads between 500 and 1500 bp) (I have a lot of reads with CSB3, but with komics I only recover 10-20% (still a good number of reads). In circularization process CSB1 and CSB2 are also chequed in komic?

I will continue playing and looking reads to understand the poor circularization oberved,
thanks
Gonzalo

**Comment by FreBio** [comment]
Hi Gonzalo,

The komics circularize does not look for csb3 mers. It assumes that the sequences provided are minicircles. The internal check for this happens during komics assemble.

Since you are working with the reads, and these reads originate from a single minicircle, wouldn't you think that the reads are already circularized, meaning that there are no overlapping sequences at the start and end of the read sequence? 
The komics circularize is developed to find overlapping ends at start and end positions of a given contig, which is assembled using short-read sequences that were generated from amplified fragments. Such a consensus sequence (contig) is expected to have overlapping ends. The komics circularize commands then chops off one of the ends to make sure that the entire sequence is unique. 
But you are not working with consensus sequences or contigs, but with reads. So I wouldn't expect any overlaps, right?

Fre

**Comment by Gon1976** [comment]
Hi Frederick

Yes! It make sense! So, assuming these reads are already "circular", polishing make CSB3 as start position for all contigs? Or only for "_circularized" marked?
Gonzalo

**Comment by FreBio** [comment]
Yes, unfortunately, komics polish will only put CSB1 at the start of the contigs when the sequence is circular. It does so by looking at the name of the sequence: if it contains 'circular', then it will put csb1 at the start. This allows you to get some kind of alignment of all your circular sequences, which is useful if you want to do clustering with vsearch.
Before putting csb1 at the start, komics polish will reorient all minicircles based the csb3 mer.
Hence, correct csb1 and csb3 mers are necessary here and can be provided. This needs to be double checked for the species you are studying. Mostly, csb3 is GGGGTTGGTGT, but there might be some variants of thse.
If you are skipping the komics circularize, you might want to make sure it is a minicircle, i.e. if it contains csb1, csb2 and csb3 mers and if its of the expected length. If you use BLAST, make sure you only retain exact hits. This is why I normally use grep, e.g. egrep 'GGGGTTGGTGT|ACACCAACCCC' to find an exact match of a given CSB3 and its reverse complement.

Hope this helps
Cheers
Fre

**Comment by Gon1976** [comment]
So, after polish only contigs marked as circular will be modified? 
I really interested in perform alignment (because I obtained much more variability than expected). But I can do it "manually". When you said reoriented, if make reverse complement of the CSB3 detected in the other strand?
Gonzalo

**Comment by FreBio** [comment]
polish will only align sequences that have 'circular' in them. But you will not have that in your fasta file, because your sequences are already circular and you wouldn't use komics circularize. Hence, you could add _circularized to the sequence headers, and then komics polish will work.
Indeed, reorientation is based on orientation of CSB3 mer. If GGGTTGGTGT, then minicircle orientation is kept. But if ACATCAACCCC, then minicircle is reverse complemented. As such, all minicircle will eventually have the same orientation.

**Comment by Gon1976** [comment]
great! thanks again!

Gonzalo

**Comment by Gon1976** [comment]
Hi @FreBio 
After finish the polish I want to move to rKomics and I don't know how to create the object "groups" to tell the species.
To try I have two circularized fasta files (am and 560R), I make a file with the names of sequences:
am.circularized.fasta, 560R.circularized.fasta (this correspond to my file in preprocess function). But I dont know wich information I should insert in "group". Both files correspond to the same specie.
Could you help-me with the R script?
Gonzalo

**Comment by gablerona** [comment]
Hello, I actually got the same error when I followed their step in their test data. but I couldnt understand how it was solved?

```

> (base) data % komics assemble --threads 4 --kmin 29 --kmax 119 --kstep 20 LCA04_run1 LCA04_trim_1.fq.gz LCA04_trim_2.fq.gz
> grep '>' LCA04_run1.maxicircles.fasta
> grep -c '>' tmp.LCA04_run1.csb3contigs.fasta
> /Users/gab/miniconda3/lib/python3.13/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.
> 
> Due to the on going maintenance burden of keeping command line application
> wrappers up to date, we have decided to deprecate and eventually remove these
> modules.
> 
> We instead now recommend building your command line and invoking it directly
> with the subprocess module.
>   warnings.warn(
> 
> Assembling contigs
> ==================
> 2025-10-12 14:46:13 - MEGAHIT v1.2.9
> 2025-10-12 14:46:13 - Using megahit_core without POPCNT and BMI2 support, because the features not detected by CPUID 
> 2025-10-12 14:46:13 - Convert reads to binary library
> 2025-10-12 14:46:14 - b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 (/Users/gab/PHD/komics/data/LCA04_trim_1.fq.gz,/Users/gab/PHD/komics/data/LCA04_trim_2.fq.gz): pe, 1923482 reads, 125 max length'
> 2025-10-12 14:46:14 - b'INFO  utils/utils.h                 :  152 - Real: 1.7762\tuser: 1.0795\tsys: 0.2672\tmaxrss: 138248192'
> 2025-10-12 14:46:14 - Start assembly. Number of CPU threads 4 
> 2025-10-12 14:46:14 - k list: 29,49,69,89,109,119 
> 2025-10-12 14:46:14 - Memory used: 4
> 2025-10-12 14:46:14 - Extract solid (k+1)-mers for k = 29 
> 2025-10-12 14:46:59 - Error occurs, please refer to /Users/gab/PHD/komics/data/tmp.LCA04_run1_megahit/LCA04_run1.log for detail
> 2025-10-12 14:46:59 - Command: /Users/gab/miniconda3/bin/megahit_core_popcnt count -k 29 -m 2 --host_mem 4 --mem_flag 1 --output_prefix /Users/gab/PHD/komics/data/tmp.LCA04_run1_megahit/tmp/k29/29 --num_cpu_threads 4 --read_lib_file /Users/gab/PHD/komics/data/tmp.LCA04_run1_megahit/tmp/reads.lib; Exit code -11
> 
> Extracting maxicircle and minicircle contigs
> ============================================
> Running BLAST with the following command:
> blastn -out /Users/gab/PHD/komics/data/tmp.LCA04_run1.maxicircle.xml -outfmt 5 -query tmp.LCA04_run1_megahit/LCA04_run1.contigs.fa -evalue 1e-06 -subject /Users/gab/miniconda3/lib/python3.13/site-packages/komics/maxicircles.fasta -task megablast -dust no
> 
> Traceback (most recent call last):
>   File "/Users/gab/miniconda3/bin/komics", line 46, in <module>
>     exec('komics.commands.' + command + '.main()')
>     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 1, in <module>
>   File "/Users/gab/miniconda3/lib/python3.13/site-packages/komics/commands/assemble.py", line 38, in main
>     ka.run()
>     ~~~~~~^^
>   File "/Users/gab/miniconda3/lib/python3.13/site-packages/komics/assemble.py", line 137, in run
>     self.blast_run()
>     ~~~~~~~~~~~~~~^^
>   File "/Users/gab/miniconda3/lib/python3.13/site-packages/komics/assemble.py", line 105, in blast_run
>     stdout, stderr=blastcmd()
>                    ~~~~~~~~^^
>   File "/Users/gab/miniconda3/lib/python3.13/site-packages/Bio/Application/__init__.py", line 591, in __call__
>     raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
> Bio.Application.ApplicationError: Non-zero return code 1 from 'blastn -out /Users/gab/PHD/komics/data/tmp.LCA04_run1.maxicircle.xml -outfmt 5 -query tmp.LCA04_run1_megahit/LCA04_run1.contigs.fa -evalue 1e-06 -subject /Users/gab/miniconda3/lib/python3.13/site-packages/komics/maxicircles.fasta -task megablast -dust no', message 'Command line argument error: Argument "query". File is not accessible:  `tmp.LCA04_run1_megahit/LCA04_run1.contigs.fa\''
> grep: LCA04_run1.maxicircles.fasta: No such file or directory
> grep: tmp.LCA04_run1.csb3contigs.fasta: No such file or directory
> 

```

I installed blast, vsearch, and megahit tho. I am not sure what could go wrong. thanks in advance!

**Comment by FreBio** [comment]
Hi there - it can't find the files LCA04_run1.maxicircles.fasta. So you need to make sure that you have downloaded this and put in the appropriate directory.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
